spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  profiles:
    active: dev

share-financialledger:
  auth:
    jwt:
      secret: #

flyway:
  locations: classpath:/db/migration
  sql-migration-suffixes: ddl
  baseline-on-migrate: true
  baseline-version: 0

---

spring:
  profiles:
    active: prod

---

spring:
  profiles:
    active: dev
