logging:
  level:
    org.hibernate.type: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/share_financialledger?useUnicode=true&charset=utf8mb4&characterEncoding=utf8
    username:
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
