logging:
  level:
    org.hibernate.type: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/share_financialledger?useUnicode=true&charset=utf8mb4&characterEncoding=utf8
    username: root # user id
    password: # user password
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

flyway:
  url: jdbc:mysql://localhost:3306/share_financialledger?serverTimezone=UTC&characterEncoding=UTF-8
  user: root # user id
  password: # user password