spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

share-financialledger:
  auth:
    jwt:
      secret: #